/**
 * VeloTools PSEO State Matrix — 30 hardcoded entries.
 * Axes: Profession × Tool (Focus Room) × Default_Config.
 * Data is server-side only; URL never invents config.
 */
/** @typedef {import('zod').infer<typeof import('./schema.mjs').MatrixEntrySchema>} MatrixEntry */

/** @type {MatrixEntry[]} */
export const MATRIX_ENTRIES = [
  {
    id: 'backend-developer-focus-room',
    profession: 'backend-developer',
    professionLabel: 'Backend Developer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for Backend Developers — Deep Work Timer | VeloTools',
    description:
      'Pomodoro timer preset for backend developers: 50/10 deep work blocks, midnight theme, lofi ambient. Runs fully in your browser.',
    h1: 'Focus Room for backend developers',
    intentBanner: 'Backend preset · 50/10 · midnight · lofi',
    config: {
      timers: { focusMinutes: 50, shortBreakMinutes: 10, longBreakMinutes: 20 },
      soundPreset: 'lofi',
      volume: 0.55,
      theme: 'midnight',
    },
  },
  {
    id: 'frontend-developer-focus-room',
    profession: 'frontend-developer',
    professionLabel: 'Frontend Developer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for Frontend Developers — UI Deep Work | VeloTools',
    description:
      'Focus timer for frontend developers: classic 25/5 Pomodoro, teal theme, cafe ambient for creative UI work. Private, client-side only.',
    h1: 'Focus Room for frontend developers',
    intentBanner: 'Frontend preset · 25/5 · teal · cafe',
    config: {
      timers: { focusMinutes: 25, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'cafe',
      volume: 0.6,
      theme: 'teal',
    },
  },
  {
    id: 'devops-engineer-focus-room',
    profession: 'devops-engineer',
    professionLabel: 'DevOps Engineer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for DevOps Engineers — Incident-Safe Timer | VeloTools',
    description:
      'Deep work timer for DevOps: 45/10 blocks, jade theme, rain ambient for calm infra work. No account, no data upload.',
    h1: 'Focus Room for DevOps engineers',
    intentBanner: 'DevOps preset · 45/10 · jade · rain',
    config: {
      timers: { focusMinutes: 45, shortBreakMinutes: 10, longBreakMinutes: 20 },
      soundPreset: 'rain',
      volume: 0.5,
      theme: 'jade',
    },
  },
  {
    id: 'ux-designer-focus-room',
    profession: 'ux-designer',
    professionLabel: 'UX Designer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for UX Designers — Research & Flow Timer | VeloTools',
    description:
      'Pomodoro for UX designers: 30/5 sessions, amber theme, forest ambient. Ideal for research synthesis and wireframing.',
    h1: 'Focus Room for UX designers',
    intentBanner: 'UX preset · 30/5 · amber · forest',
    config: {
      timers: { focusMinutes: 30, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'forest',
      volume: 0.55,
      theme: 'amber',
    },
  },
  {
    id: 'ui-designer-focus-room',
    profession: 'ui-designer',
    professionLabel: 'UI Designer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for UI Designers — Pixel Focus Timer | VeloTools',
    description:
      'Focus timer for UI designers: 25/5 Pomodoro, midnight theme, lofi beats. Browser-only privacy for design sprints.',
    h1: 'Focus Room for UI designers',
    intentBanner: 'UI preset · 25/5 · midnight · lofi',
    config: {
      timers: { focusMinutes: 25, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'lofi',
      volume: 0.65,
      theme: 'midnight',
    },
  },
  {
    id: 'copywriter-focus-room',
    profession: 'copywriter',
    professionLabel: 'Copywriter',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for Copywriters — Writing Sprint Timer | VeloTools',
    description:
      'Writing timer for copywriters: 25/5 sprints, teal theme, cafe ambient (coffee-shop effect). Nothing leaves your device.',
    h1: 'Focus Room for copywriters',
    intentBanner: 'Copywriter preset · 25/5 · teal · cafe',
    config: {
      timers: { focusMinutes: 25, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'cafe',
      volume: 0.7,
      theme: 'teal',
    },
  },
  {
    id: 'content-writer-focus-room',
    profession: 'content-writer',
    professionLabel: 'Content Writer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for Content Writers — Longform Timer | VeloTools',
    description:
      'Longform writing preset: 40/8 blocks, amber theme, rain ambient. Client-side Pomodoro with zero server sync.',
    h1: 'Focus Room for content writers',
    intentBanner: 'Content preset · 40/8 · amber · rain',
    config: {
      timers: { focusMinutes: 40, shortBreakMinutes: 8, longBreakMinutes: 20 },
      soundPreset: 'rain',
      volume: 0.55,
      theme: 'amber',
    },
  },
  {
    id: 'product-manager-focus-room',
    profession: 'product-manager',
    professionLabel: 'Product Manager',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for Product Managers — Spec Deep Work | VeloTools',
    description:
      'Deep work timer for PMs: 35/7 blocks, midnight theme, ocean ambient. Spec writing without distractions or accounts.',
    h1: 'Focus Room for product managers',
    intentBanner: 'PM preset · 35/7 · midnight · ocean',
    config: {
      timers: { focusMinutes: 35, shortBreakMinutes: 7, longBreakMinutes: 20 },
      soundPreset: 'ocean',
      volume: 0.5,
      theme: 'midnight',
    },
  },
  {
    id: 'data-analyst-focus-room',
    profession: 'data-analyst',
    professionLabel: 'Data Analyst',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for Data Analysts — Analysis Sprint Timer | VeloTools',
    description:
      'Analysis sprint timer: 50/10 deep blocks, jade theme, rain ambient. Private local sessions for spreadsheet and SQL work.',
    h1: 'Focus Room for data analysts',
    intentBanner: 'Analyst preset · 50/10 · jade · rain',
    config: {
      timers: { focusMinutes: 50, shortBreakMinutes: 10, longBreakMinutes: 25 },
      soundPreset: 'rain',
      volume: 0.45,
      theme: 'jade',
    },
  },
  {
    id: 'qa-engineer-focus-room',
    profession: 'qa-engineer',
    professionLabel: 'QA Engineer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for QA Engineers — Test Pass Timer | VeloTools',
    description:
      'Test-pass focus timer: 25/5 Pomodoro, teal theme, forest ambient. Stay sharp through regression runs — data stays local.',
    h1: 'Focus Room for QA engineers',
    intentBanner: 'QA preset · 25/5 · teal · forest',
    config: {
      timers: { focusMinutes: 25, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'forest',
      volume: 0.5,
      theme: 'teal',
    },
  },
  {
    id: 'student-focus-room',
    profession: 'student',
    professionLabel: 'Student',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for Students — Study Pomodoro Timer | VeloTools',
    description:
      'Study Pomodoro for students: classic 25/5, amber theme, lofi ambient. Free, offline-friendly, no signup.',
    h1: 'Focus Room for students',
    intentBanner: 'Student preset · 25/5 · amber · lofi',
    config: {
      timers: { focusMinutes: 25, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'lofi',
      volume: 0.6,
      theme: 'amber',
    },
  },
  {
    id: 'freelancer-focus-room',
    profession: 'freelancer',
    professionLabel: 'Freelancer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for Freelancers — Billable Deep Work | VeloTools',
    description:
      'Billable deep-work timer: 45/10 blocks, midnight theme, cafe ambient. Track focus without sending client notes to a server.',
    h1: 'Focus Room for freelancers',
    intentBanner: 'Freelancer preset · 45/10 · midnight · cafe',
    config: {
      timers: { focusMinutes: 45, shortBreakMinutes: 10, longBreakMinutes: 20 },
      soundPreset: 'cafe',
      volume: 0.6,
      theme: 'midnight',
    },
  },
  {
    id: 'seo-specialist-focus-room',
    profession: 'seo-specialist',
    professionLabel: 'SEO Specialist',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for SEO Specialists — Audit Sprint Timer | VeloTools',
    description:
      'SEO audit sprint timer: 30/5 blocks, jade theme, rain ambient. Long-tail research without cloud sync of notes.',
    h1: 'Focus Room for SEO specialists',
    intentBanner: 'SEO preset · 30/5 · jade · rain',
    config: {
      timers: { focusMinutes: 30, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'rain',
      volume: 0.55,
      theme: 'jade',
    },
  },
  {
    id: 'mobile-developer-focus-room',
    profession: 'mobile-developer',
    professionLabel: 'Mobile Developer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for Mobile Developers — Build Sprint Timer | VeloTools',
    description:
      'Mobile build sprint timer: 40/8 blocks, teal theme, lofi ambient. Client-side focus for Xcode and Android Studio sessions.',
    h1: 'Focus Room for mobile developers',
    intentBanner: 'Mobile preset · 40/8 · teal · lofi',
    config: {
      timers: { focusMinutes: 40, shortBreakMinutes: 8, longBreakMinutes: 20 },
      soundPreset: 'lofi',
      volume: 0.55,
      theme: 'teal',
    },
  },
  {
    id: 'sysadmin-focus-room',
    profession: 'sysadmin',
    professionLabel: 'Sysadmin',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    title: 'Focus Room for Sysadmins — Maintenance Window Timer | VeloTools',
    description:
      'Maintenance-window timer: 50/10 blocks, midnight theme, fire ambient. Calm focus for late-night ops — fully private.',
    h1: 'Focus Room for sysadmins',
    intentBanner: 'Sysadmin preset · 50/10 · midnight · fire',
    config: {
      timers: { focusMinutes: 50, shortBreakMinutes: 10, longBreakMinutes: 25 },
      soundPreset: 'fire',
      volume: 0.45,
      theme: 'midnight',
    },
  },
  // Second wave: alternate timing/sound variants for high-intent professions
  {
    id: 'backend-developer-focus-room-ultradian',
    profession: 'backend-developer',
    professionLabel: 'Backend Developer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'ultradian',
    title: '90-Minute Deep Work Timer for Backend Developers | VeloTools',
    description:
      'Ultradian 90/20 deep work for backend engineers. Jade theme, ocean ambient. Browser-only — no telemetry.',
    h1: '90-minute deep work for backend developers',
    intentBanner: 'Backend ultradian · 90/20 · jade · ocean',
    config: {
      timers: { focusMinutes: 90, shortBreakMinutes: 20, longBreakMinutes: 30 },
      soundPreset: 'ocean',
      volume: 0.4,
      theme: 'jade',
    },
  },
  {
    id: 'copywriter-focus-room-sprint',
    profession: 'copywriter',
    professionLabel: 'Copywriter',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'sprint',
    title: '15-Minute Writing Sprint Timer for Copywriters | VeloTools',
    description:
      'Fast 15/3 writing sprints for copywriters. Amber theme, rain ambient. Ideal for headline and hook batches.',
    h1: '15-minute writing sprints for copywriters',
    intentBanner: 'Copywriter sprint · 15/3 · amber · rain',
    config: {
      timers: { focusMinutes: 15, shortBreakMinutes: 3, longBreakMinutes: 10 },
      soundPreset: 'rain',
      volume: 0.65,
      theme: 'amber',
    },
  },
  {
    id: 'student-focus-room-exam',
    profession: 'student',
    professionLabel: 'Student',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'exam',
    title: 'Exam Prep Pomodoro Timer for Students — 50/10 | VeloTools',
    description:
      'Exam prep timer: 50/10 blocks, midnight theme, forest ambient. Study without accounts or cloud notebooks.',
    h1: 'Exam prep Pomodoro for students',
    intentBanner: 'Student exam · 50/10 · midnight · forest',
    config: {
      timers: { focusMinutes: 50, shortBreakMinutes: 10, longBreakMinutes: 25 },
      soundPreset: 'forest',
      volume: 0.5,
      theme: 'midnight',
    },
  },
  {
    id: 'ux-designer-focus-room-research',
    profession: 'ux-designer',
    professionLabel: 'UX Designer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'research',
    title: 'UX Research Synthesis Timer — 45/10 Focus Room | VeloTools',
    description:
      'Research synthesis preset for UX: 45/10, teal theme, cafe ambient. Affinity mapping without uploading notes.',
    h1: 'UX research synthesis timer',
    intentBanner: 'UX research · 45/10 · teal · cafe',
    config: {
      timers: { focusMinutes: 45, shortBreakMinutes: 10, longBreakMinutes: 20 },
      soundPreset: 'cafe',
      volume: 0.55,
      theme: 'teal',
    },
  },
  {
    id: 'devops-engineer-focus-room-oncall',
    profession: 'devops-engineer',
    professionLabel: 'DevOps Engineer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'oncall',
    title: 'On-Call Calm Timer for DevOps — Short Focus Blocks | VeloTools',
    description:
      'On-call friendly 20/5 blocks, amber theme, fire ambient. Stay sharp between alerts — all state stays local.',
    h1: 'On-call calm timer for DevOps',
    intentBanner: 'DevOps on-call · 20/5 · amber · fire',
    config: {
      timers: { focusMinutes: 20, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'fire',
      volume: 0.4,
      theme: 'amber',
    },
  },
  {
    id: 'frontend-developer-focus-room-css',
    profession: 'frontend-developer',
    professionLabel: 'Frontend Developer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'css',
    title: 'CSS Polish Focus Timer for Frontend Developers | VeloTools',
    description:
      'CSS polish sessions: 30/5, jade theme, lofi ambient. Pixel-perfect work without leaving the browser sandbox.',
    h1: 'CSS polish focus timer for frontend developers',
    intentBanner: 'Frontend CSS · 30/5 · jade · lofi',
    config: {
      timers: { focusMinutes: 30, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'lofi',
      volume: 0.6,
      theme: 'jade',
    },
  },
  {
    id: 'data-analyst-focus-room-sql',
    profession: 'data-analyst',
    professionLabel: 'Data Analyst',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'sql',
    title: 'SQL Query Focus Timer for Data Analysts | VeloTools',
    description:
      'SQL deep-focus: 40/8, midnight theme, cafe ambient. Query writing with private local session history.',
    h1: 'SQL focus timer for data analysts',
    intentBanner: 'Analyst SQL · 40/8 · midnight · cafe',
    config: {
      timers: { focusMinutes: 40, shortBreakMinutes: 8, longBreakMinutes: 20 },
      soundPreset: 'cafe',
      volume: 0.5,
      theme: 'midnight',
    },
  },
  {
    id: 'product-manager-focus-room-roadmap',
    profession: 'product-manager',
    professionLabel: 'Product Manager',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'roadmap',
    title: 'Roadmap Writing Timer for Product Managers | VeloTools',
    description:
      'Roadmap writing blocks: 50/10, teal theme, forest ambient. Strategy docs stay on your machine.',
    h1: 'Roadmap writing timer for product managers',
    intentBanner: 'PM roadmap · 50/10 · teal · forest',
    config: {
      timers: { focusMinutes: 50, shortBreakMinutes: 10, longBreakMinutes: 25 },
      soundPreset: 'forest',
      volume: 0.5,
      theme: 'teal',
    },
  },
  {
    id: 'qa-engineer-focus-room-regression',
    profession: 'qa-engineer',
    professionLabel: 'QA Engineer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'regression',
    title: 'Regression Testing Focus Timer for QA | VeloTools',
    description:
      'Regression pass timer: 45/10, midnight theme, rain ambient. Steady pacing for long test suites.',
    h1: 'Regression testing focus timer for QA',
    intentBanner: 'QA regression · 45/10 · midnight · rain',
    config: {
      timers: { focusMinutes: 45, shortBreakMinutes: 10, longBreakMinutes: 20 },
      soundPreset: 'rain',
      volume: 0.45,
      theme: 'midnight',
    },
  },
  {
    id: 'content-writer-focus-room-blog',
    profession: 'content-writer',
    professionLabel: 'Content Writer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'blog',
    title: 'Blog Drafting Pomodoro for Content Writers | VeloTools',
    description:
      'Blog drafting preset: 25/5, jade theme, cafe ambient. Draft faster with coffee-shop noise — zero cloud drafts.',
    h1: 'Blog drafting Pomodoro for content writers',
    intentBanner: 'Content blog · 25/5 · jade · cafe',
    config: {
      timers: { focusMinutes: 25, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'cafe',
      volume: 0.65,
      theme: 'jade',
    },
  },
  {
    id: 'freelancer-focus-room-deadline',
    profession: 'freelancer',
    professionLabel: 'Freelancer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'deadline',
    title: 'Deadline Sprint Timer for Freelancers — 20/5 | VeloTools',
    description:
      'Deadline sprints: 20/5, amber theme, lofi ambient. Ship client work with private local streaks.',
    h1: 'Deadline sprint timer for freelancers',
    intentBanner: 'Freelancer deadline · 20/5 · amber · lofi',
    config: {
      timers: { focusMinutes: 20, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'lofi',
      volume: 0.7,
      theme: 'amber',
    },
  },
  {
    id: 'seo-specialist-focus-room-briefs',
    profession: 'seo-specialist',
    professionLabel: 'SEO Specialist',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'briefs',
    title: 'Content Brief Focus Timer for SEO Specialists | VeloTools',
    description:
      'Content brief blocks: 35/7, teal theme, ocean ambient. Keyword briefs without syncing notes to third parties.',
    h1: 'Content brief timer for SEO specialists',
    intentBanner: 'SEO briefs · 35/7 · teal · ocean',
    config: {
      timers: { focusMinutes: 35, shortBreakMinutes: 7, longBreakMinutes: 20 },
      soundPreset: 'ocean',
      volume: 0.55,
      theme: 'teal',
    },
  },
  {
    id: 'mobile-developer-focus-room-debug',
    profession: 'mobile-developer',
    professionLabel: 'Mobile Developer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'debug',
    title: 'Mobile Debug Focus Timer — 50/10 Deep Blocks | VeloTools',
    description:
      'Debug deep blocks: 50/10, amber theme, rain ambient. Crash investigation with calm private focus.',
    h1: 'Mobile debug focus timer',
    intentBanner: 'Mobile debug · 50/10 · amber · rain',
    config: {
      timers: { focusMinutes: 50, shortBreakMinutes: 10, longBreakMinutes: 25 },
      soundPreset: 'rain',
      volume: 0.4,
      theme: 'amber',
    },
  },
  {
    id: 'sysadmin-focus-room-docs',
    profession: 'sysadmin',
    professionLabel: 'Sysadmin',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'docs',
    title: 'Runbook Writing Timer for Sysadmins | VeloTools',
    description:
      'Runbook writing: 30/5, jade theme, forest ambient. Document procedures without uploading internal notes.',
    h1: 'Runbook writing timer for sysadmins',
    intentBanner: 'Sysadmin docs · 30/5 · jade · forest',
    config: {
      timers: { focusMinutes: 30, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'forest',
      volume: 0.5,
      theme: 'jade',
    },
  },
  {
    id: 'ui-designer-focus-room-critique',
    profession: 'ui-designer',
    professionLabel: 'UI Designer',
    tool: 'focus-room',
    toolLabel: 'Focus Room',
    variant: 'critique',
    title: 'Design Critique Prep Timer for UI Designers | VeloTools',
    description:
      'Critique prep: 20/5, teal theme, ocean ambient. Review flows privately before stakeholder meetings.',
    h1: 'Design critique prep timer for UI designers',
    intentBanner: 'UI critique · 20/5 · teal · ocean',
    config: {
      timers: { focusMinutes: 20, shortBreakMinutes: 5, longBreakMinutes: 15 },
      soundPreset: 'ocean',
      volume: 0.55,
      theme: 'teal',
    },
  },
];
